# 仓库配置
repository:
  url: "https://github.com/TanStack/router.git"
  branch: "main"

# 所有路径都相对于项目根目录
workspace_dir: "./repo-workspace"
output_dir: "./repo-pdfs"

# PDF 设置
pdf_settings:
  margin: "margin=1in"
  main_font: "Songti SC"
  mono_font: "SF Mono"

# 忽略的文件或目录
ignores:
  - "node_modules"
  - "dist"
  - "build"
  - ".git"
  - "__pycache__"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - ".DS_Store"
  - "*.log"