# 仓库配置
repository:
  url: "https://github.com/bmadcode/BMAD-METHOD.git"
  branch: "main"

# 所有路径都相对于项目根目录
workspace_dir: "./repo-workspace"
output_dir: "./repo-pdfs"

# 设备预设配置
device_preset: "desktop"  # 可选值: desktop, kindle7, tablet, mobile
# 或使用环境变量: DEVICE=kindle7 make

# PDF 设置
pdf_settings:
  margin: "margin=1in"
  main_font: "Noto Serif CJK SC"
  mono_font: "DejaVu Sans Mono"
  highlight_style: "monochrome"
  split_large_files: true  # 将大文件分割成多个部分而不是截断
  
  # 字体大小设置（可被设备预设覆盖）
  fontsize: "10pt"
  code_fontsize: "\\small"  # 代码字体大小
  
  # 布局设置
  linespread: "1.0"  # 行间距
  parskip: "6pt"     # 段落间距
  
  metadata:
    author: "Repo-to-PDF Generator"
    creator: "LaTeX"
    producer: "XeLaTeX"

# 设备特定配置预设
device_presets:
  desktop:
    description: "桌面端阅读优化"
    template: "default"
    pdf_overrides:
      margin: "margin=1in"
      fontsize: "10pt"
      code_fontsize: "\\small"
      linespread: "1.0"
      
  kindle7:
    description: "7英寸Kindle设备优化"
    template: "kindle"
    pdf_overrides:
      margin: "margin=0.4in"
      fontsize: "10pt"  # 提升到10pt，确保可读性
      code_fontsize: "\\small"  # 使用\small(9pt)而不是\scriptsize(7pt)
      linespread: "0.95"  # 稍微增加行间距
      parskip: "4pt"  # 增加段落间距
      max_file_size: "200KB"
      max_line_length: 60
      
  tablet:
    description: "平板设备阅读优化"
    template: "technical"  
    pdf_overrides:
      margin: "margin=0.6in"
      fontsize: "9pt"
      code_fontsize: "\\small"
      linespread: "0.95"
      
  mobile:
    description: "手机端阅读优化"
    template: "kindle"
    pdf_overrides:
      margin: "margin=0.3in"
      fontsize: "7pt"
      code_fontsize: "\\tiny"
      linespread: "0.85"
      parskip: "2pt"

# 忽略的文件或目录
ignores:
  # 依赖和构建相关
  - "node_modules"
  - "dist"
  - "build"
  - "coverage"
  - ".next"
  - ".nuxt"
  - "vendor"
  - ".vaunt"
  - ".github"

  # 锁定文件
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "composer.lock"
  - "Gemfile.lock"
  - "poetry.lock"
  - "Cargo.lock"      # Rust
  - "mix.lock"        # Elixir
  - "deno.lock"       # Deno
  - "bun.lockb"       # Bun
  - "shrinkwrap.yaml" # npm
  - "flake.lock"      # Nix
  - "gradle.lockfile" # Gradle
  - "Pipfile.lock"    # Python pipenv
  - "pdm.lock"        # Python PDM
  - "requirements.txt.lock" # Python pip-tools
  - ".mockery.yaml"

  # 缓存和临时文件
  - ".git"
  - "__pycache__"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - ".DS_Store"
  - "*.log"
  - ".cache"
  - ".temp"
  - "tmp"

  # IDE 和编辑器
  - ".idea"
  - ".vscode"
  - "*.swp"
  - "*.swo"
  - ".project"
  - ".settings"

  # 其他
  - "docs/"
  - "docs/swagger.json"
  - "docs/swagger.yaml"
