# 仓库配置
repository:
  url: "https://github.com/PatrickJS/awesome-cursorrules.git"
  branch: "main"

# 所有路径都相对于项目根目录
workspace_dir: "./repo-workspace"
output_dir: "./repo-pdfs"

# PDF 设置
pdf_settings:
  margin: "margin=1in"
  main_font: "Songti SC"
  mono_font: "SF Mono"
  highlight_style: "monochrome"
  metadata:
    author: "Repo-to-PDF Generator"
    creator: "LaTeX"
    producer: "XeLaTeX"

# 忽略的文件或目录
ignores:
  # 依赖和构建相关
  - "node_modules"
  - "dist"
  - "build"
  - "coverage"
  - ".next"
  - ".nuxt"
  - "vendor"
  - ".vaunt"
  - ".github"

  # 锁定文件
  - "package-lock.json"
  - "yarn.lock"
  - "pnpm-lock.yaml"
  - "composer.lock"
  - "Gemfile.lock"
  - "poetry.lock"
  - "Cargo.lock"      # Rust
  - "mix.lock"        # Elixir
  - "deno.lock"       # Deno
  - "bun.lockb"       # Bun
  - "shrinkwrap.yaml" # npm
  - "flake.lock"      # Nix
  - "gradle.lockfile" # Gradle
  - "Pipfile.lock"    # Python pipenv
  - "pdm.lock"        # Python PDM
  - "requirements.txt.lock" # Python pip-tools

  # 缓存和临时文件
  - ".git"
  - "__pycache__"
  - "*.pyc"
  - "*.pyo"
  - "*.pyd"
  - ".DS_Store"
  - "*.log"
  - ".cache"
  - ".temp"
  - "tmp"

  # IDE 和编辑器
  - ".idea"
  - ".vscode"
  - "*.swp"
  - "*.swo"
  - ".project"
  - ".settings"

  # 其他
  - "docs/release"
  - "docs/swagger.json"
  - "docs/swagger.yaml"
